[versions]
coroutines = "1.10.2"
kotlin = "2.2.21"
springboot = "4.0.0"
spotless = "7.0.2"
java = "17"
ktlintVersion = "0.50.0"
arrow = "2.0.1"
dependencycheck = "12.1.1"
swaggerUi = "5.20.1"
kover = "0.9.1"
uri = "0.0.19"
dss = "6.2"

[libraries]
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
arrow-core-serialization = { module = "io.arrow-kt:arrow-core-serialization", version.ref = "arrow" }
swagger-ui = { module = "org.webjars:swagger-ui", version.ref = "swaggerUi" }
uri = { module = "com.eygraber:uri-kmp", version.ref = "uri" }
dss-service = { module = "eu.europa.ec.joinup.sd-dss:dss-service", version.ref = "dss" }
dss-validation = { module = "eu.europa.ec.joinup.sd-dss:dss-validation", version.ref = "dss" }
dss-tsl-validation = { module = "eu.europa.ec.joinup.sd-dss:dss-tsl-validation", version.ref = "dss" }
dss-utils-apache-commons = { module = "eu.europa.ec.joinup.sd-dss:dss-utils-apache-commons", version.ref = "dss" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springboot" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "dependencycheck" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
